# Generated by Django 2.2.7 on 2022-12-01 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_seafood'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeatKebab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kebab_choice', models.CharField(max_length=200)),
                ('small_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('large_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('category_description', models.TextField()),
            ],
            options={
                'verbose_name': 'List of Meat Kebab',
                'verbose_name_plural': 'List of Meat Kebab',
            },
        ),
        migrations.CreateModel(
            name='Soup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'verbose_name': 'List of Soup',
                'verbose_name_plural': 'List of Soup',
            },
        ),
        migrations.CreateModel(
            name='VegetarianKebab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kebab_choice', models.CharField(max_length=200)),
                ('small_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('large_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('category_description', models.TextField()),
            ],
            options={
                'verbose_name': 'List of Vegetarian Kebab',
                'verbose_name_plural': 'List of Vegetarian Kebab',
            },
        ),
    ]
