# Generated by Django 2.2.7 on 2022-12-02 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_drink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kebab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kebab_name', models.CharField(max_length=200)),
                ('small_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('large_price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'verbose_name': 'List of Kebabs',
                'verbose_name_plural': 'List of Kebabs',
            },
        ),
        migrations.DeleteModel(
            name='MeatKebab',
        ),
        migrations.DeleteModel(
            name='VegetarianKebab',
        ),
    ]
