# Generated by Django 2.2.7 on 2022-12-14 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20221202_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_title', models.CharField(max_length=200)),
                ('food_gif', models.ImageField(upload_to='media')),
                ('food_description', models.TextField()),
            ],
            options={
                'verbose_name': 'Food',
                'verbose_name_plural': 'Food',
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_title', models.CharField(max_length=100)),
                ('slide_image', models.ImageField(upload_to='')),
                ('slide_sub_title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'List of meals',
                'verbose_name_plural': 'List of meals',
            },
        ),
    ]
