# Generated by Django 2.2.7 on 2022-12-14 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_food_slide'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slide',
            options={},
        ),
    ]
