# Generated by Django 2.2.7 on 2022-12-14 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_auto_20221214_1904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slide',
            options={'verbose_name': 'Slide', 'verbose_name_plural': 'Slides'},
        ),
        migrations.RenameField(
            model_name='slide',
            old_name='slide_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='slide',
            old_name='slide_sub_title',
            new_name='sub_title',
        ),
        migrations.RenameField(
            model_name='slide',
            old_name='slide_title',
            new_name='title',
        ),
    ]
