# Generated by Django 2.2.7 on 2022-12-18 19:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_auto_20221214_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('username', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('score', models.FloatField(default=-1, validators=[django.core.validators.MaxValueValidator(5.0), django.core.validators.MinValueValidator(0.0)])),
            ],
        ),
    ]
