# Generated by Django 2.2.7 on 2022-12-18 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_delete_reviewrating'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Slide',
            new_name='Meals',
        ),
        migrations.AlterModelOptions(
            name='meals',
            options={'verbose_name': 'Meal', 'verbose_name_plural': 'Meals'},
        ),
    ]
