# Generated by Django 2.2.7 on 2022-12-23 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_auto_20221223_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meals',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='meals',
            name='score',
            field=models.IntegerField(default=1),
        ),
    ]
